# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:stat.*'

# 検索キーワード
keywords:
        ASR: 4
        learning theory: 3
        small sample size: 3
        generalization error: 4
        MLP: 3
        transformer: 3
        kaggle: 3
        nlp: 3
        anomaly detection: 1

# 通知の閾値
score_threshold: 3
